###################################################################################################################################
Welcome {name}, you are in front the big wooden door of castle. There is no doubt you have courage to reach here,
but way to MIA is not easy from here.  
To reach MIA you have to pass {totalStage} stages. When you enter this door, you will be at stage one.
At every stage there are three streets. One will be at your left, one will be at your right and one will be in front of you.
You can choose where you want to go. Out of these 3 streets, 2 streets are clear and full of fun but one of the street has monster 
or could be any trouble. If you encounter monster or trouble you have top deal with it first then only you can proceed from there.
At any point of time you can hit HELP to know the available command. When you are ready please enter PLAY to start the Game.
####################################################################################################################################
