@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  
 ||||||||     //\\       ||       ||\\      //||  \\      //  ||||||||     //\\
 ||    ||    //  \\      ||    	  || \\    // ||   \\    //   ||    ||	  //  \\	
 ||||||||   //    \\     ||	  ||  \\  //  ||    \\  //    ||||||||   //    \\
 ||        //======\\    ||	  ||   ---    ||     \\//     ||\\	//======\\
 ||       //        \\   ||  	  ||          ||      ||      || \\    //        \\
 ||      //          \\  ||====== ||          ||      ||      ||  \\  //          \\
      
     
           		|||||||      //\\       |||||||||  ==========   ||	    ||||||||||
			||     	    //  \\      ||	       ||   	||	    ||
			||	   //    \\     |||||||||      ||	||	    |||||||||	
			||	  //======\\           ||      ||	||	    ||	
			|||||||	 //	   \\	|||||||||      ||	|||||||||   |||||||||||

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

			Welcome to the PALMYRA CASTLE 1.0

There was a far far away kingdom, where lived an old king named "ALFONSO". He had a beautiful
daughter princess "MIA". MIA  was the most beautiful girl in the whole kingomd and king loved 
her very much. There was the beast "ALEXENDRO" who has eyes on the princess. He came with the
proposal to the king for his daughter but was rejected  disgracefully  by the king. To avenge 
his Slander , he  broke into  princess castle and took her as  his prisoner. Princess MIA was 
taken to the PALMYRA CASTLE where she was kept under the watch full eyes of his faithful army
of hounds, zombies, crocodiles, one eye monsters, dragon etc.

The king in distrace has called for a urgent meetings with his loyal advisors ERIC and JULIAN.
They suggested only 2 people in whole kingdom are capable of defeating the beast and his ugly
monsters. The king sent in a royal decree calling for help to save his dear princess to

 ***  NICOLAS  - THE ROYAL COMMANDER-IN-CHIEF
 ***  GEOFFREY - THE ULTIMATE WIZRD

NICOLAS is good with Weapon, his every strike damage the opponent twice compare to any other 
fighter.
GEOFFREY has some magical powers which make him extraordinary powerful.


To Play this game player can be one of the two NICOLAS or GEOFFREY. PLayer will be loaded with
their respective powers and can start the battle against ALEXENDRO and his army.
		 
